"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%h0=okx57_5*kwjx=a@m0*ud650zz(1qj_y-fqvh*30i)fon3@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# For local leave this blank also works on production.
ALLOWED_HOSTS = []

# This one is for pa production.
#ALLOWED_HOSTS = ["timetable.pythonanywhere.com"]


# Application definition

INSTALLED_APPS = [

# Try removing this when you put myPolls into the python lib as a package.
    # Watch out for this I think it was autogenerated, should be
    # a cap P here  |  I worked a fix for it though.

    #'myPolls.apps.MypollsConfig',  # works on local and pa and is the original.

    'myPolls',   # This works on local and production.

    #'myPolls.apps.MyPollsConfig',  # Does not work.

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

# We added this from the tutorial 7, customize the admin page
# this references our /mysite/templates/admin/base_site.html
# I deleted index.html it was fucking shit up.  I changed the name so
# it doesn't get accessed anymore, it must be depricated or something.
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/  #databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Vancouver'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

# Don't forget to run this everytime you add a static file:
# python manage.py collectstatic  see 16 in your Davee_ReadMe.txt
# if you don't want to.


# This is used as the var in the html file
# rel="stylesheet" type="text/css"
#     href="{% static 'myPolls/style.css' %}" />
#                |
STATIC_URL = '/static/'

"""
The STATIC_ROOT variable in settings.py defines the single folder
you want to collect all your static files into. Typically, this
would be a top-level folder inside your project.
"""

# NOTE: No STATIC_ROOT works on both local and production
# maybe you are not using any static files!

# Local:

#STATIC_ROOT = 'c:/Daves_Python_Programs/pythonAnyWhere/mysite/myPolls/static'


# Production:
# The STATIC_ROOT on the pa web tab (under Static files section
# scroll way down there) must be the same as this one.
#/home/my-username/my-django-project/static

STATIC_ROOT = '/home/timetable/mysite/myPolls/static'


# STATIC_ROOT doesn't exist when you first create a new project.
# Docs say you can also do this:
# STATIC_ROOT = os.path.join(BASE_DIR, "static")









